### PR TITLE
Flags to get compiling with GNU and clean up some copyrights

### PR DESCRIPTION
**Pull request by danholdaway**
- Add compiler flags for GNU.
- Clean up compiler flags for Intel.
- Minor code change to get things to compile with GNU
- Clean up the copyright so UCAR does not appear.
- Outgrads is not found so does not compile with debug flags, needed for CI @ JCSDA

### CODE REVIEW

**Comment by rtodling** [comment]
Perhaps you didn't see what I wrote on Teams over the weekend, but this branch you are trying to merge to is already obsolete. I made important changes on another branch that I had pushed over to the GitHub, but had no PR on it. This was this is the branch I am planning to turn into develop. Although nothing you have here interferes w/ what I've done, I'd prefer not to merge to the branch you point to here. 
The branch I am referring to is: feature/rtodling/multi_outer_loops

**Comment by danholdaway** [comment]
@rtodling I was thinking we could have just merged into that branch and then into your branch. But we can equally do it the other way around so I merged your branch into mine and changed the base. You should see the proper base branch now.

**Review by rtodling — APPROVED** [review]
Dan, thank you for this. Thanks for re-basing and thanks for removing the PR w/ the removed trailing spaces; I am glad to hear that Don things gsibclim should be handled as an outside packaged; that's what I think it should be. 

Of the changes here there two things:

1) the commenting out of outgrads1 in hybrid_isotropic code: I will take your changes, but immediately reverse them; I will simply add the missing routine. The reason you found this as a missing routine is likely a link option: intel doesn't care about a routine that's never in the path of calls; the gnu link is probably set to care ... not a big deal; I will provide the routine, as I put the hybrid feature back, I want for this to work.

2) somehow m_nc_GEOSens.F90 has changes related to clearing the trailing parts ... that's not a problem. That's new code w/ no other baseline to compare against anyway; so no problem.

**Comment by rtodling** [comment]
BTW: I see there is a single line actual change in m_nc_GEOSens ... thanks

**Pull request merged**
